- docs/contributing/contributing.rst
This PR adds docs about updated sass setup (so far everything is non-breaking)
> Add docs about new sass setup

- docs/contributing/contributing.rst
Addresses comments from #9
/cc @evildmp
> Correct capitalisation in `Sass`

- cms/static/cms/gulpfile.js
> Better gulp errors

- docs/contributing/contributing.rst
Generalize frontend setup and add section for iconfont
> Add documentation for iconfont

- cms/static/cms/sass/cms.toolbar.modal.scss
- cms/static/cms/sass/cms.toolbar.sideframe.scss
- cms/static/cms/sass/settings/_all.scss
> Scss variables for modal and sideframe standalone stylesheets

- cms/static/cms/gulpfile.js
- cms/static/cms/js/modules/cms.app_hook_select.js
- cms/static/cms/js/modules/cms.base.js
- cms/static/cms/js/modules/cms.changeform.js
- cms/static/cms/js/modules/cms.changelist.js
- cms/static/cms/js/modules/cms.clipboard.js
- cms/static/cms/js/modules/cms.modal.js
- cms/static/cms/js/modules/cms.plugins.js
- cms/static/cms/js/modules/cms.sideframe.js
- cms/static/cms/js/modules/cms.structureboard.js
- cms/static/cms/js/modules/cms.toolbar.js
this only addresses jshint
jscs would follow in the next pr
> fix or shadow all jshint errors

- .editorconfig
- cms/static/cms/js/modules/cms.app_hook_select.js
- cms/static/cms/js/modules/cms.base.js
- cms/static/cms/js/modules/cms.changeform.js
- cms/static/cms/js/modules/cms.changelist.js
- cms/static/cms/js/modules/cms.clipboard.js
- cms/static/cms/js/modules/cms.modal.js
- cms/static/cms/js/modules/cms.plugins.js
- cms/static/cms/js/modules/cms.sideframe.js
- cms/static/cms/js/modules/cms.structureboard.js
- cms/static/cms/js/modules/cms.toolbar.js
the docs will follow
the travis setup we'll figure out later on
> JSCS linting

- RELEASE_INFO
- docs/contributing/contributing.rst
Sadly I forgot to add documentation to bundling setup in https://github.com/FinalAngel/django-cms/pull/55 - so here it is
> JS bundling docs

- .travis.yml
- cms/tests/frontend/karma.conf.js
- cms/tests/frontend/unit/cms.base.test.js
~~explanation will follow~~
so the problem is that saucelabs is failing a lot because of connection/concurrency problems between travis / saucelabs, so my idea is to make it opt-in until it's resolved through the commit message
this pr adds that functionality
> Use saucelabs on demand

- cms/tests/frontend/unit/cms.base.test.js
> skip tests that require localstorage if it is not actually supported

- cms/tests/frontend/unit/cms.modal.test.js
- cms/tests/frontend/unit/fixtures/modal.html
remaining tests for the modal
coverage for the modal is 46.35%
> cms modal close tests

- cms/tests/frontend/integration/run_testserver.sh
- docs/contributing/testing.rst
- testserver.py
* Use separate file with djangocms-helper runner and settings	
* Docs: update integrations tests section with a simpler test server command
> Testserver settings

- cms/tests/frontend/.jshintrc
- cms/tests/frontend/integration/toolbar.js
> toolbar show/hide

- cms/tests/frontend/integration/logout.js
- cms/tests/frontend/integration/settings/messages.js
> logout integration tests

- cms/tests/frontend/karma.conf.js
otherwise it tries to run it locally
> fix condition to run saucelabs

- cms/tests/frontend/integration/addFirstPage.js
- cms/tests/frontend/integration/settings/globals.js
- cms/tests/frontend/integration/settings/messages.js
- testserver.py
> first page creation

- cms/tests/frontend/integration/addFirstPage.js
- cms/tests/frontend/integration/loginToolbar.js
- cms/tests/frontend/integration/logout.js
- cms/tests/frontend/integration/settings/messages.js
> publish & toolbar login

- cms/tests/frontend/integration/settings/globals.js
- cms/tests/frontend/integration/settings/messages.js
- cms/tests/frontend/integration/users.js
> user profile

- cms/tests/frontend/integration/createContent.js
- cms/tests/frontend/integration/loginAdmin.js
- cms/tests/frontend/integration/newPage.js
- cms/tests/frontend/integration/settings/messages.js
- cms/tests/frontend/integration/users.js
- gulpfile.js
> add content suite fix

- cms/tests/frontend/integration/settings/messages.js
- cms/tests/frontend/integration/switchLanguage.js
- gulpfile.js
> Switch language integration test

- cms/tests/frontend/integration/addFirstPage.js
- cms/tests/frontend/integration/createContent.js
- cms/tests/frontend/integration/loginAdmin.js
- cms/tests/frontend/integration/loginToolbar.js
- cms/tests/frontend/integration/logout.js
- cms/tests/frontend/integration/newPage.js
- cms/tests/frontend/integration/settings/globals.js
- cms/tests/frontend/integration/settings/messages.js
- cms/tests/frontend/integration/sideframe.js
- cms/tests/frontend/integration/switchLanguage.js
- cms/tests/frontend/integration/toolbar.js
- cms/tests/frontend/integration/users.js
- cms/tests/frontend/karma.conf.js
> clean localstorage & wait for toolbar

- cms/tests/frontend/integration/editMode.js
- cms/tests/frontend/integration/settings/messages.js
- gulpfile.js
> page edit mode

- cms/tests/frontend/integration/editContent.js
- cms/tests/frontend/integration/settings/messages.js
- gulpfile.js
> Implement edit content integration test

- cms/tests/frontend/integration/editContentTools.js
- cms/tests/frontend/integration/settings/messages.js
- gulpfile.js
> Implement edit page content utils integration test

- cms/test_utils/project/templates/integration/base.html
- cms/test_utils/project/templates/integration/fullwidth.html
- cms/test_utils/project/templates/integration/page.html
- cms/tests/frontend/integration/createContent.js
- cms/tests/frontend/integration/editContent.js
- cms/tests/frontend/integration/editContentTools.js
- cms/tests/frontend/integration/newPage.js
- cms/tests/frontend/integration/switchLanguage.js
- test_requirements/requirements_base.txt
- testserver.py
Part of https://divio-ch.atlassian.net/browse/CMS-882
NOTE: had to add .ready(1s) to prevent problems of form submit after user pastes copied content and BE data haven't been created yet /cc @dhorelik
> Test templates improvement

- cms/tests/frontend/unit/cms.base.test.js
use async `beforeEach` than async `it`, no other code changes
> refactor base tests to be less async

- cms/static/cms/js/modules/cms.plugins.js
- cms/tests/frontend/unit/cms.messages.test.js
- cms/tests/frontend/unit/cms.plugins.test.js
- cms/tests/frontend/unit/cms.toolbar.test.js
- cms/tests/frontend/unit/fixtures/plugins.html
- cms/tests/frontend/unit/fixtures/toolbar.html
first part of the tests for the plugin, decided to push it now, because it will become too unwieldy
- no longer required to wait for document ready
- add an extra assertion to the messages 
as usual it's easier to check https://github.com/FinalAngel/django-cms/pull/109/files?w=1 because changes in the cms.plugins.js are mostly whitespace 
also the fixture is quite big, but it's a copy from the source, no need to check it too thoroughly :)
> Plugins tests

- cms/static/cms/js/modules/cms.navigation.js
- cms/tests/frontend/unit/cms.modal.test.js
- cms/tests/frontend/unit/cms.navigation.test.js
- there is no public API for cms.navigation so there's not much tests either
- remove the wait for dom ready
as usual better to review with https://github.com/FinalAngel/django-cms/pull/115/files?w=1 because changes in cms.navigation.js are mostly indentation
> cms navigation tests

- cms/tests/frontend/integration/dragndrop.js
- cms/tests/frontend/integration/helpers/cms.js
- gulpfile.js
It wasn't nearly as trivial as it looks
- changed login helper to be more stable
- add test for dragging one placeholder to another
> Drag plugin from one placeholder to another

- cms/tests/frontend/integration/dragndrop.js
- cms/tests/frontend/integration/helpers/cms.js
- made logout clear localStorage
- added the test for dragging into nested plugin
> add dragndrop test for nested plugins

- cms/tests/frontend/integration/addNewUser.js
- cms/tests/frontend/integration/disableToolbar.js
- cms/tests/frontend/integration/helpers/cms.js
- cms/tests/frontend/integration/settings/globals.js
- cms/tests/frontend/integration/users.js
- gulpfile.js
finished add-new-user.js
extended gulpfile
extended cms.js
extended globals.js
> Feature/integration tests/adds new user

- cms/tests/frontend/integration/pageControl.js
- gulpfile.js
- test_requirements/requirements_base.txt
Important: updates admin-style
> Page control tests

- cms/tests/frontend/integration/pageControl.js
- cms/tests/frontend/integration/publish.js
- gulpfile.js
previously linting wasn't failing on travis, now it does
> fail build on lint

- cms/tests/frontend/integration/changeSettings.js
- gulpfile.js
> Feature/integration tests/change settings

- cms/tests/frontend/integration/clipboard.js
- cms/tests/frontend/integration/pageControl.js
- gulpfile.js
> tests for clipboard

- cms/tests/frontend/integration/helpers/cms.js
- cms/tests/frontend/integration/wizard.js
- gulpfile.js
- Create a new sub page through "Page > Add Page" (double click)
- Create a new sub page using the "Creation Wizard" (pick and click on "Next")
- Check that you can go back in creation wizard
> Wizard tests

- cms/tests/frontend/integration/helpers/cms.js
- cms/tests/frontend/integration/pageControl.js
- cms/tests/frontend/integration/permissions.js
- cms/tests/frontend/integration/wizard.js
- gulpfile.js
- testserver.py
> Permissions

- cms/tests/frontend/integration/dragndrop.js
- try to drag into a parent that doesn't accept child plugins of this type
> add test for "not allowed" to drop case

- cms/test_utils/project/templates/integration/base.html
- cms/tests/frontend/integration/createContent.js
- cms/tests/frontend/integration/loginToolbar.js
- cms/tests/frontend/integration/narrowScreen.js
- cms/tests/frontend/integration/wizard.js
- gulpfile.js
- Check that the login form works on mobile (tablet, desktop etc)
- Check that the toolbar menu works on mobile and tablet
> Narrow screen tests

- cms/tests/frontend/integration/sideframe.js
also removes incorrect test for sideframe not being closed after reload
> add a test for iframe resizing

- cms/tests/frontend/integration/helpers/cms.js
- cms/tests/frontend/integration/history.js
- cms/tests/frontend/integration/revertLive.js
- gulpfile.js
- testserver.py
add reversion to testserver
finished revertLive.js
finished history.js
> Feature/integration tests/history

- cms/tests/frontend/integration/addFirstPage.js
- cms/tests/frontend/integration/createContent.js
- cms/tests/frontend/integration/helpers/cms.js
- cms/tests/frontend/integration/wizard.js
merging latest upstream enabled the ckeditor for text content
> change the way content is filled for wizard

- cms/tests/frontend/integration/clipboard.js
- test_requirements/requirements_base.txt
- testserver.py
had to add aldryn_bootstrap3 to the test project (it has perfect col/row plugins)
- adds test for pasting plugins into plugins with child restrictions (through paste button and dragndrop)
- adds test for pasting plugins with parent restriction into plugins (through paste button and dragndrop)
(ref https://github.com/divio/django-cms/pull/4914)
> Pasting restrictions

- cms/tests/frontend/integration/clipboard.js
- cms/tests/frontend/integration/createContent.js
- cms/tests/frontend/integration/dragndrop.js
- cms/tests/frontend/integration/editContent.js
- cms/tests/frontend/integration/editContentTools.js
- cms/tests/frontend/integration/helpers/cms.js
- add cms.switchTo('structure' || 'content') helper
- add cms.expandPlaceholderPlugins('.cms-dragarea selector') helper
> Add more testing helpers

- cms/admin/pageadmin.py
> Fixes copying page to be child of another page

- .travis.yml
- cms/tests/frontend/unit/cms.base.test.js
not that we merged upstream coverage dropped a bit
> missing test

- cms/tests/frontend/unit/cms.modal.test.js
tests for some of the private methods
> Modal private tests

- cms/static/cms/js/modules/cms.modal.js
- cms/tests/frontend/unit/cms.modal.test.js
> Modal private methods unit tests

- cms/static/cms/js/modules/cms.modal.js
- cms/tests/frontend/unit/cms.modal.test.js
- cms/tests/frontend/unit/fixtures/modal.html
after this there's only one left, the one that happens when iframe loads
> Unit tests for modal private methods

- cms/static/cms/js/modules/cms.modal.js
- cms/tests/frontend/unit/cms.modal.test.js
- cms/tests/frontend/unit/html/modal_iframe.html
- cms/tests/frontend/unit/html/modal_iframe_errorlist.html
- cms/tests/frontend/unit/html/modal_iframe_errornote.html
- cms/tests/frontend/unit/html/modal_iframe_messages.html
- cms/tests/frontend/unit/html/modal_iframe_title.html
> tests for loadIframe

- cms/tests/frontend/integration/pagetree.js
Lef on page tree:
- After reload, current state is stored (open / closed nodes) - currently doesn't
- Test search and filters (drag&drop should be disabled then)
> add tests for cutting and pasting pages
